server:
  port: 9002

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://175.178.108.7:3306/health?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&serverTimezone=Hongkong&allowMultiQueries=true&nullCatalogMeansCurrent=true
      username: root
      password: TT9pC9oNq8y!&BMq

dubbo:
  application:
    name: health-backend
  registry:
    address: zookeeper://175.178.108.7:2181
    ## 设置连接超时时间 60s
    timeout: 60000
  consumer:
    check: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
